version: '3.8'

services:
  iotbackend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - 32990:80
      - 32991:443
    depends_on:
      - migration
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbConnection="Server=db;Port=5432;Database=IOTBackend;Username=postgres;Password=postgres"

  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=IOTBackend

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbConnection="Server=db;Port=5432;Database=IOTBackend;Username=postgres;Password=postgres"
